apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis
  name: redis-controller
  namespace: demo-ops
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis-controller
    spec:
      containers:
      - image: aws_account_id.dkr.ecr.region.amazonaws.com/redis
        name: redis
        ports:
        - containerPort: 6379
          name: redis-port
        volumeMounts:
        - name: redis-persistent-storage
          mountPath: /var/lib/redis
      volumes:
      - name: redis-persistent-storage
        persistentVolumeClaim:
          claimName: pv-claim-db
      imagePullSecrets:
        - name: docker-pass