apiVersion: v1
kind: Service
metadata:
  labels:
    name: redisservice
  name: redisdb
  namespace: demo-ops
spec:
  ports:
    - port: 6379
      targetPort: 6379
  selector:
    name: redis-controller