apiVersion: v1
kind: Service
metadata:
  name: web
  labels:
    name: web
  namespace: kube-system
spec:
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8000
      protocol: TCP
  selector:
    app: web